### ISSUE TITLE
when I end process of lpfw I lose connection until reboot

### ISSUE THREAD

**Issue by kensully** [themighty1/lpfw#11]
Hi,
First of all thank you for puplishing your project. It's valuable.
I have an issue with it in my system. I am on Ubuntu 14.04.2 32 bit platform. When I close the `lpfw` process I lose  connection. None of the applications is able to  connect. I have to reboot my system.
I wonder how I can reset connection after closing `lpfw` .
Regards.
Kenn

**Comment by themighty1** [comment]
Hi, run 
sudo iptables -F
to disable all iptables rules
