### ISSUE TITLE
Fails to run, fixed with "#!/usr/bin/python" in gui.py

### ISSUE THREAD

**Issue by Ansholy1951** [themighty1/lpfw#17]
Running on Ubuntu 14.04.3 LTS Trusty, the gui.py file refused to run.
Adding "!/usr/bin/python" shebang fixed it.

Love the code, thanks a bunch.

- Duckling

**Comment by TheOncomingStorm** [comment]
That fix worked here as well. Thanks.

**Comment by themighty1** [comment]
Thanks for bringing it to my attention.
The README says it should be run as
python gui/gui.py

Did you try that?

**Comment by studersi** [comment]
I created a pull request for this fix: https://github.com/themighty1/lpfw/pull/19/.

With the shebang, the script can be launched with both methods:
* `python ./gui.py`
* `./gui.py`
