### ISSUE TITLE
Error starting lpfw. _nfct_open (NFNL_SUBSYS_CTNETLINK, 0) results in "Error 93 - Protocol not supported"

### ISSUE THREAD

**Issue by khalilfazal** [themighty1/lpfw#2]
When I launch lpfw with `sudo ./lpfw` I get:

    nfct_open: Protocol not supported,
    Error 93 - Protocol not supported
    nfct_open returned NULL
    Dumping a core file. Make sure to sudo chmod 0777 it to make it user-readable

I traced the origin of the error messages to line 111 in conntrack.c

    nfct_handle *handle_flush = _nfct_open (NFNL_SUBSYS_CTNETLINK, 0);

That query calls `nfct_open(NFNL_SUBSYS_CTNETLINK, 0)` which returns NULL, aborting the program.

**Comment by khalilfazal** [comment]
It claims that it has dumped a core file. Where is this file?

**Comment by themighty1** [comment]
Thank you for reporting.
Core dumps must be located in the same dir where lpfw is.
Does your Linux distro have conntrack enabled in the kernel?

**Comment by khalilfazal** [comment]
I can't get conntrack to work. I'm unable to find help elsewhere. When I run `conntrack -E` I get:

    conntrack v1.4.2 (conntrack-tools): Can't open handler

**Comment by themighty1** [comment]
Maybe you can tell me what Linux distro you are running and we can go from there?
