### ISSUE TITLE
32-bit system specific issue - program internet access not blocked when not in rules

### ISSUE THREAD

**Issue by junkvolny** [themighty1/lpfw#3]
On fresh install of Kubuntu 14.04 within VirtualBox, I start xchat irc client, firewall asks if block, and during this time xchat already connects and loads. After I click deny/block, and I restart xchat, it's blocked fine.

On the other hand, Firefox was blocked during dialog and could not connect.

Am I missing something here?
![xchat_1st_start_connects_while_dialog_runs](https://cloud.githubusercontent.com/assets/12115270/7420616/2f757848-ef7e-11e4-956b-1a137ee007a8.png)
![xchat_2nd_start_denied](https://cloud.githubusercontent.com/assets/12115270/7420617/2f75e6d4-ef7e-11e4-9a01-e170c93d00d0.png)

**Comment by themighty1** [comment]
Appreciate the screenshots. What you are describing is a catastrophic failure. I'm pretty confident it cannot happen. So, please help me get to the bottom of it.
Can you post here everything that shows up on the sudo ./lpfw console at the time when xchat exhibits the behaviour (not the console for python gui/gui.py)

**Comment by junkvolny** [comment]
At the time it shows:
<TCP remote 185.30.166.38:8001 local 51350 /usr/bin/xchat 2381 (asking frontend) drop
nfq_handle - raddr: 192.168.1.1 laddr:10.0.2.15
socket not found in cache 
socket found with state:07
in socket handle 
found among active processes 
<UDP remote 192.168.1.1:53 local 23066 /usr/sbin/dnsmasq 1147 allow
nfq_handle - raddr: 185.30.166.38 laddr:10.0.2.15
in socket handle 
found after searching procfd 
<TCP remote 185.30.166.38:8001 local 51350 /usr/bin/xchat 2381 (frontend busy) drop
nfq_handle - raddr: 185.30.166.38 laddr:10.0.2.15
in socket handle 
found among active processes 
<TCP remote 185.30.166.38:8001 local 51350 /usr/sbin/nmbd 1298 allow


Also might help the output of netstat (active connections):
kubuntu@kubuntu-VirtualBox:~$ netstat -p -n -A  inet | grep xchat
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
tcp        0      0 10.0.2.15:41625         148.251.187.147:8001    ESTABLISHED 3085/xchat     

Longer log:
http://pastebin.com/7xFk0tmu

If I search IP there, I found e.g. section:
nfq_handle - raddr: 148.251.187.147 laddr:10.0.2.15
socket not found in cache
socket found with state:02
in socket handle 
found after searching procfd 
<TCP remote 148.251.187.147:8001 local 41625 /usr/bin/xchat 3085 (asking frontend) drop

To me it seems it identified all well, it logged dropping, so how come I see alive TCP connection? (confused)

**Comment by themighty1** [comment]
Are you using the latest 64-bit kubuntu iso from http://www.kubuntu.org/getkubuntu?

**Comment by junkvolny** [comment]
32-bit ISO, Kubuntu 14.04, yes, as of now latest
For VirtualBox testing, 32-bit seemed enough.

**Comment by themighty1** [comment]
ok, will try the 32-bit iso. I guess the 32-bitness may be the root of the issue.

**Comment by themighty1** [comment]
Thank you for your report. Im confirming that the bug exists on 32-bit ubuntu and it appears to be one that needs some time to debug. My code call NF_DROP as expected, yet the connection is still allowed to go through. Maybe a bug in system libs somewhere.

I will try to debug it and also will update README to say that 32-bit ubuntu are not supported.
In the meantime feel free to use 64-bit ubuntu.

**Comment by junkvolny** [comment]
I am confirming the behavior: I just tested with Kubuntu 14.04 64-bit version, and unlike Kubuntu 14.04 32-bit version, it works as expected, XChat gets blocked. Weird. If it's bug in system libs, shouldn't we report it somewhere?

**Comment by themighty1** [comment]
Thank your effort. Turns out it was my bug which I just fixed
https://github.com/themighty1/lpfw/commit/771d315bb5aff5f5a0cc6e5c35e5793684d1572f
Because i didnt zero out a var on a new itration + didnt check for errors. Lesson learned.
This also affects 64-bit system but for some reason didnt manifest itself during testing.

**Comment by junkvolny** [comment]
I can confirm it is fixed, I just tested it on original system where it didn't work before.
