### ISSUE TITLE
ICMP not working (ping)

### ISSUE THREAD

**Issue by junkvolny** [themighty1/lpfw#4]
According to README, ICMP protocol should work, unless two or more applications are using it. Program "ping" is used on command line to test latency of network, and uses ICMP protocol: http://en.wikipedia.org/wiki/Ping_%28networking_utility%29

However, when using only ping (e.g. $ ping github.com ), firewall blocks it and prints on output repeating lines:
nfq_handle - raddr: 192.30.252.130 laddr:10.0.2.15
unknown protocol, dropping packet 1

Also it seems you incorrectly identify ICMP protocol number as 5 instead of 1:
https://github.com/themighty1/lpfw/blob/master/common/defines.h
#define PROTO_ICMP 5
Wiki says otherwise: http://en.wikipedia.org/wiki/List_of_IP_protocol_numbers
ICMP should be number 1, not 5.
However simple editing of #define does not help, code needs some fix, too.

Tested on Kubuntu 14.04 (both 32-bit and 64-bit is same), Linux 3.13.0-32-generic.

**Comment by themighty1** [comment]
Sorry, for the confusion.
While the int socket_handle_icmp() function is still in the code from the previous maintainer, I havent gotten around to understanding all the corner cases of icmp parsing. So, ICMP is not available, I will update the README.

**Comment by junkvolny** [comment]
Please also change in README:
"If your system happens to use any other transport protocol besides TCP/UDP/ICMP and you don't want those packets discarded by lpfw ..."
To: ... TCP/UDP ...

**Comment by junkvolny** [comment]
I see you fixed it, thanks.
