### ISSUE TITLE
fatal-errors

### ISSUE THREAD

**Issue by Mahdi321** [themighty1/lpfw#42]
```
~/Downloads/lpfw-master$ make
g++ -g -fpermissive -std=c++11 -Wfatal-errors -c sha256/sha256.c
g++ -g -fpermissive -std=c++11 -Wfatal-errors -c base64.cpp
g++ -g -fpermissive -std=c++11 -Wfatal-errors -c conntrack.c
g++ -g -fpermissive -std=c++11 -Wfatal-errors -c testmain.cpp
g++ -g -fpermissive -std=c++11 -Wfatal-errors -c argtable/argtable2.c
argtable/argtable2.c: In function ‘void arg_print_formatted(FILE*, unsigned int, unsigned int, const char*)’:
argtable/argtable2.c:974:17: error: ‘isspace’ was not declared in this scope
         while ( isspace(*(text+line_start)) )
                 ^~~~~~~
compilation terminated due to -Wfatal-errors.
Makefile:19: recipe for target 'argtable2.o' failed
make: *** [argtable2.o] Error 1
```

**Comment by licaon-kter** [comment]
Detail you OS, compiler version, etc

**Comment by Mahdi321** [comment]
(note I'm noob)
Ubuntu 18.04 64x
g++ was 7
but with g++ 6: 
`$ make
g++ -g -fpermissive -std=c++11 -Wfatal-errors -c sha256/sha256.c
g++ -g -fpermissive -std=c++11 -Wfatal-errors -c base64.cpp
g++ -g -fpermissive -std=c++11 -Wfatal-errors -c conntrack.c
g++ -g -fpermissive -std=c++11 -Wfatal-errors -c testmain.cpp
g++ -g -fpermissive -std=c++11 -Wfatal-errors -c argtable/argtable2.c
argtable/argtable2.c: In function ‘void arg_print_formatted(FILE*, unsigned int, unsigned int, const char*)’:
argtable/argtable2.c:974:43: error: ‘isspace’ was not declared in this scope
         while ( isspace(*(text+line_start)) )
                                           ^
compilation terminated due to -Wfatal-errors.
Makefile:19: recipe for target 'argtable2.o' failed
make: *** [argtable2.o] Error 1
`

**Comment by cspack77** [comment]
Same error here. Arch Linux, gcc 8.2.1

**Comment by jadolg** [comment]
anyone fixed this?

**Comment by planetRocker** [comment]
alternative firewall ? :)
