### ISSUE TITLE
code bug (function m_printf_file)

### ISSUE THREAD

**Issue by junkvolny** [themighty1/lpfw#5]
A bit of evening reading of https://github.com/themighty1/lpfw/blob/master/lpfw.cpp showed me your function with bug:
...
int m_printf_file ( const int loglevel, const char * logstring )
switch ( loglevel ) {
...
case MLOG_ALERT: //Alerts get logged unconditionally to all log channels
      write ( fileno ( filelogdebug_stream ), "ALERT: ", strlen ( logstring ) );
      return 0;
    }
}
I am sure you meant instead:
write ( fileno ( filelogdebug_stream ), "ALERT: ", strlen ("ALERT: ") );
write ( fileno ( filelogdebug_stream ), logstring, strlen ( logstring ) );

Also I noticed comment:
//technically vfprintf followed by fsync should be enough, but for some reason on my system it can take more than 1 minute before data gets actually written to disk. So until the mystery of such a huge delay is solved, we use write() so data gets written to dist immediately
And I wondered if you did not forget using fflush() before fsync() after vfprintf() in your previous function version where you got delays. fsync() flushes OS cache (memory->disk, seen even when power off), fflush() flushes your application cache (OS can still cache but other programs see updated version). so vfprintf() + fflush() = same as write(); fsync() for both = remember even if kernel down/power off.

**Comment by themighty1** [comment]
Thank you for your feedback.
m_printf* functions are left over from the original C version and are not in use in the code. They are left for reference until i fully finish porting logging.
Luckily there's no need to deal with low-level filesystem access anymore.
